Feature/ming 52 토스 결제하기
ming-veloper/ming-commerce pull request #33
Opened 2023-02-16 07:25 UTC by yeonnex

## 개발 상세 내용

토스 결제와 주문 엔티티에 주문 이름 속성을 추가하였습니다.

## Jira Ticket (지라 이슈 번호를 적어 연결합니다.)

- [MING-52](https://ming-commerce.atlassian.net/browse/MING-52)

## 테스트 방법을 적습니다.(필요시)

어떻게 테스트를 진행해야 하는지 적습니다.

## PR 요청시 테스트해야 하는 항목을 적고 테스트한 내용을 체크합니다.

- [ ] (필요한 경우) `lint`에 통과
- [ ] (필요한 경우) `유닛 테스트`에 통과
- [ ] 다음 기능에 대한 테스트를 포함
    - [ ] 입력 기능 (Insert)
    - [ ] 수정 기능 (Update)
    - [ ] 삭제 기능 (Delete)
    - [ ] 조회 기능 (Select)
- [ ] 브라우저별 테스트를 진행
    - [ ] Chrome
    - [ ] Firefox
    - [ ] Safari
    - [ ] IE 11

[MING-52]: https://ming-commerce.atlassian.net/browse/MING-52?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-02-18 06:50 UTC, twosom requested changes
흠... 전체적으로 다시 한 번 검토해보시겠어요?

2023-02-18 06:50 UTC, twosom commented on src/main/java/com/ming/mingcommerce/order/service/OrderService.java
>          String orderName = order.extractOrderName();
`orderName`을 `Order` 객체에게 추출을 부탁하고 그걸 다시 `Order`에 주입하는 것은 OOP 관점에서도 뭔가 어색한 것 같아요. 누구 책임으로 할 것인지 명확하게 하는 것이 좋아보입니다~^_^

2023-02-20 10:34 UTC, yeonnex commented on src/main/java/com/ming/mingcommerce/order/service/OrderService.java
>          String orderName = order.extractOrderName();
@twosom 네 전체적으로 코드 수정 및 리팩토링 완료했습니다. `결제승인` 기능과 더불어 `주문조회` 기능까지 커밋으로 구분하여 구현했습니다. 결제 완료시 `주문조회` api 를 사용하여 리다이렉트 해주시면 될 것 같습니다!

2023-02-20 10:52 UTC, twosom requested changes
조금만 더 다듬어주면 될 것 같습니다~~!

2023-02-20 10:52 UTC, twosom commented on src/main/java/com/ming/mingcommerce/order/controller/OrderController.java
> +        return new ResponseEntity<>(response, HttpStatus.OK);
`OrderService#validate` 로직을 `OrderService#getOrder` 안에서 수행해도 괜찮을 것 같습니다만...

2023-02-20 10:52 UTC, twosom commented on src/main/java/com/ming/mingcommerce/payment/controller/PaymentController.java
> +        return new ResponseEntity<>(response, HttpStatus.OK);
`PaymentService#validateAmount`는 `PaymentService#pay` 내부에서 호출해도 좋을 것 같아요.

2023-02-20 10:52 UTC, twosom commented on src/main/java/com/ming/mingcommerce/payment/service/PaymentService.java
> +
`PaymentService#validateAmount`는 외부로 공개하지 않아도 될 것 같아요. 내부 호출로 충분해 보인달까...

2023-02-20 11:18 UTC, yeonnex commented on src/main/java/com/ming/mingcommerce/order/controller/OrderController.java
> +        return new ResponseEntity<>(response, HttpStatus.OK);
네, 검증 작업을 `OrderService#getOrder` 의 책임으로 보는게 더 좋을 것 같네요.

2023-02-20 11:22 UTC, yeonnex commented on src/main/java/com/ming/mingcommerce/payment/controller/PaymentController.java
> +        return new ResponseEntity<>(response, HttpStatus.OK);
바로 위에 남겨주신 `OrderService#validate`와 같은 맥락이네요... ㅎㅎ 😅

2023-02-20 11:23 UTC, yeonnex commented on src/main/java/com/ming/mingcommerce/payment/service/PaymentService.java
> +
네 private 으로 바꾸었고, 인터페이스 `PaymentService#validateAmount` 함수도 삭제했습니다.

2023-02-21 06:27 UTC, yeonnex commented
> 조금만 더 다듬어주면 될 것 같습니다~~!

PayService 테스트코드 작성과 다듬기 완료했습니다. 확인 부탁드릴게요! 😊

2023-02-21 10:26 UTC, twosom approved these changes
LGTM! 
여러개로 흩어진 커밋을 하나로 뭉친 다음 polishing 작업을 하였습니다~!

2023-02-21 10:27 UTC, merged

2023-02-21 10:34 UTC, twosom commented
#31 완료하였으므로 해당 이슈 닫겠습니다.