이메일 인증 횟수 제한과 인증 메일 본문에 프론트 url 매핑
ming-veloper/ming-commerce pull request #53
Opened 2023-03-12 16:01 UTC by yeonnex

## 개발 상세 내용

1시간에 1번만 이메일 인증을 위한 메일 발송이 가능하게 하였습니다. 추후 하루 5회 이하 횟수 제한 기능도 넣도록 하겠습니다. 메일 본문에 삽입되는 이메일 인증을 위한 프론트 URL 은 _**/update-user?token&email**_ 로 하였습니다.

## Jira Ticket (지라 이슈 번호를 적어 연결합니다.)

- [MING-77](https://ming-commerce.atlassian.net/browse/MING-77)

## 테스트 방법을 적습니다.
**MemberTest**#`issueEmailCheckToken`

## PR 요청시 테스트해야 하는 항목을 적고 테스트한 내용을 체크합니다.

- [ ] (필요한 경우) `lint`에 통과
- [ ] (필요한 경우) `유닛 테스트`에 통과
- [ ] 다음 기능에 대한 테스트를 포함
    - [ ] 입력 기능 (Insert)
    - [ ] 수정 기능 (Update)
    - [ ] 삭제 기능 (Delete)
    - [ ] 조회 기능 (Select)
- [ ] 브라우저별 테스트를 진행
    - [ ] Chrome
    - [ ] Firefox
    - [ ] Safari
    - [ ] IE 11

2023-03-12 16:07 UTC, twosom requested changes
검토 부탁드려요~

2023-03-12 16:07 UTC, twosom commented on src/main/java/com/ming/mingcommerce/member/controller/MemberController.java
>          if (!(authentication.getPrincipal() instanceof CurrentMember currentMember))
사용자가 모바일에서 변경 요청을 보낸 후 PC에서 메일을 확인하게 되는 경우에는 어떻게 되는건가요?
PC에서는 JWT 토큰을 가지고 있지 않으니 해당 API는 실패할 것 같아요.
제 생각에는 이 API에서는 인증 로직을 수행하면 안될 것 같아요.
`SecurityConfig`에서도 `permitAll`로 해야 할 것 같습니다~^_^

2023-03-12 16:07 UTC, twosom commented on src/main/java/com/ming/mingcommerce/member/controller/MemberController.java
>          if (!(authentication.getPrincipal() instanceof CurrentMember currentMember))
그리고 사용자를 JWT 토큰으로 가져오는 것이 아닌 컨트롤러 매개변수로 받은 `token` 으로는 사용자를 찾을 수 없나요?

2023-03-13 04:04 UTC, yeonnex commented on src/main/java/com/ming/mingcommerce/member/controller/MemberController.java
>          if (!(authentication.getPrincipal() instanceof CurrentMember currentMember))
아 모바일로 확인하는 경우를 생각하지 못했네요 🥶
말씀하신 것처럼 JWT 를 통한 인증이 필요도 없고, 해서도 안되네요...!
사용자 정보(**Member** 엔티티 필드)로 `token`을 저장했습니다. `token`으로 사용자 특정하여 찾을 수 있습니다.

수정하여 다시 올리겠습니다.

2023-03-13 05:11 UTC, yeonnex commented
수정하여 반영하였습니다. 검토 부탁드릴게요 🚀 @twosom

2023-03-13 14:33 UTC, twosom requested changes
LGTM~!

2023-03-13 14:34 UTC, twosom approved these changes
LGTM!

2023-03-13 14:34 UTC, merged