Feature/ming 81 주문 상세 조회 이슈
ming-veloper/ming-commerce pull request #56
Opened 2023-03-18 12:12 UTC by yeonnex

## 개발 상세 내용

`orderId` 에 해당하는 주문 상세 조회시, 주문상품들에 대한 리스트 정보함께 가져오려했으나, jpql 에서 chlid collection 을 가져올 수 없는 한계가 있었습니다.

차선책으로, 우선 orderId 를 사용하여 주문에 대한 정보(주문이름, 주문총액, 주문날짜)를 가져온 다음, 주문 상품에 대한 쿼리를 한번 더 날려 이를 자바 애플리케이션 상에서 조합하여 반환하는 형식을 사용했습니다.

## Jira Ticket (지라 이슈 번호를 적어 연결합니다.)

- [MING-81](https://ming-commerce.atlassian.net/browse/MING-81)

## 테스트 방법을 적습니다.(필요시)

어떻게 테스트를 진행해야 하는지 적습니다.

## PR 요청시 테스트해야 하는 항목을 적고 테스트한 내용을 체크합니다.

- [ ] (필요한 경우) `lint`에 통과
- [ ] (필요한 경우) `유닛 테스트`에 통과
- [ ] 다음 기능에 대한 테스트를 포함
    - [ ] 입력 기능 (Insert)
    - [ ] 수정 기능 (Update)
    - [ ] 삭제 기능 (Delete)
    - [ ] 조회 기능 (Select)
- [ ] 브라우저별 테스트를 진행
    - [ ] Chrome
    - [ ] Firefox
    - [ ] Safari
    - [ ] IE 11

2023-03-18 18:04 UTC, twosom requested changes
검토 부탁드립니다~~

2023-03-18 18:04 UTC, twosom commented on src/main/java/com/ming/mingcommerce/order/respository/OrderRepository.java
> +    OrderDetail getOrderDetail(String orderId);
`getOrderDetail` 이라는 메소드 이름이 맞는지 검토가 필요하겠네요.
`detail` 이라는 단어를 내포하면서 정작 가져오는 항목들은 `orderName`, `totalAmount`, `createdDate` 뿐이라서요.
게다가 아래의 `getMyOrderDetail`이랑은 어떤 차이가 있는건지도 코드를 보는 입장에서 헷갈릴 수도 있겠어요~

2023-03-18 18:04 UTC, twosom commented on src/main/java/com/ming/mingcommerce/order/respository/OrderRepository.java
>      Page<MyOrderModel> getMyOrder(String memberUuid, Pageable pageable);
지금 작성한 코드는 아니지만 메소드 이름에 대해서 논의할 필요가 있을 듯 합니다... 사용자 주문 `목록`은 `getMyOrder`보다는 `getMyOrders`나 `getMyOrderList` 같은 복수형이 나은 것 같아요.🥹

2023-03-19 07:34 UTC, yeonnex commented on src/main/java/com/ming/mingcommerce/order/respository/OrderRepository.java
>      Page<MyOrderModel> getMyOrder(String memberUuid, Pageable pageable);
호곡쓰 😅 오해의 소지가 다분하군요... 메서드명 바꿔서 다시 올리겠습니다. 😎 `getMyOrderList` 가 좋아보이네요!

2023-03-19 08:41 UTC, twosom commented on src/main/java/com/ming/mingcommerce/order/respository/OrderRepository.java
>      Page<MyOrderModel> getMyOrder(String memberUuid, Pageable pageable);
`Page<MyOrderModel>`은 컬렉션입니다.

2023-03-20 02:42 UTC, yeonnex commented on src/main/java/com/ming/mingcommerce/order/respository/OrderRepository.java
> +    OrderDetail getOrderDetail(String orderId);
`getSimpleOrderDetail` 어떨까요?

2023-03-20 14:51 UTC, twosom commented on src/main/java/com/ming/mingcommerce/order/model/OrderDetail.java
> +        this.createDate = order.getCreatedDate();
만약에 `OrderDetail` 클래스에서 `productDetailList`를 사용하고 있는 곳이 없다면 해당 프로퍼티 제거 후에 생성자에서 `this(order.getOrderName(), order.getTotalAmount(), order.getCreatedDate())`
도 고려해볼 만 한 것 같아요.
물론 기본 생성자는 `private` 으로 만드는게 좋겠죠.

2023-03-21 01:58 UTC, yeonnex commented on src/main/java/com/ming/mingcommerce/order/model/OrderDetail.java
> +    private List<ProductDetail> productDetailList = new ArrayList<>();
확인결과, **전혀 없네요...**  삭제하겠습니다.

2023-03-21 02:01 UTC, yeonnex commented on src/main/java/com/ming/mingcommerce/order/model/OrderDetail.java
> +        this.createDate = order.getCreatedDate();
네 그게 더 코드량이 줄어 보기 좋네요!

2023-03-21 02:07 UTC, yeonnex commented on src/main/java/com/ming/mingcommerce/order/model/OrderProductDetail.java
> +        this.productDetailList = productDetailList;
와우.. 코드가 뚱뚱해졌는데 굉장히 날씬해졌네요... 굿 👍@twosom

2023-03-21 11:12 UTC, twosom approved these changes
LGTM!

2023-03-21 11:12 UTC, merged